const $=id=>document.getElementById(id);const auth=$('auth'),profile=$('profile'),matching=$('matching'),chatScreen=$('chatScreen');const loginTab=$('loginTab'),registerTab=$('registerTab'),authBtn=$('authBtn'),authError=$('authError'),authUsername=$('authUsername'),authPassword=$('authPassword');let mode='login',user=null,username='',micOn=true,cameraOn=true,localStream=null,remoteStream=null,pc=null,signal=null,role=null,pollTimer=null,pollBusy=false,pendingIce=[];function show(el){el.classList.remove('hidden')}function hide(el){el.classList.add('hidden')}function addMessage(text,who='system'){const d=document.createElement('div');d.className=who==='me'?'message mine':who==='them'?'message theirs':'system-message';d.textContent=text;$('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight}function status(t){let old=document.querySelector('.video-status');if(old)old.remove();let el=document.createElement('span');el.className='video-status';el.textContent=t;document.querySelector('.videos').appendChild(el);setTimeout(()=>el.remove(),2500)}
async function api(url,opts={}){const r=await fetch(url,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed');return data}
function setMode(m){mode=m;loginTab.classList.toggle('active',m==='login');registerTab.classList.toggle('active',m==='register');authBtn.textContent=m==='login'?'Login →':'Create Account →';authError.textContent=''}loginTab.onclick=()=>setMode('login');registerTab.onclick=()=>setMode('register');
async function loadMe(){try{const d=await api('/api/me');user=d.user;showProfile()}catch{show(auth);hide(profile)}}function showProfile(){hide(auth);show(profile);$('profileName').textContent='@'+user.username;$('profileSince').textContent='Member since '+new Date(user.createdAt).toLocaleDateString();}
authBtn.onclick=async()=>{authError.textContent='';try{const d=await api('/api/'+mode,{method:'POST',body:JSON.stringify({username:authUsername.value.trim(),password:authPassword.value})});user=d.user;authPassword.value='';showProfile()}catch(e){authError.textContent=e.message}};
$('logoutBtn').onclick=async()=>{await api('/api/logout',{method:'POST'});user=null;hide(profile);show(auth)};
async function startCamera(){try{localStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:{echoCancellation:true,noiseSuppression:true}});const lv=$('localVideo');lv.srcObject=localStream;lv.muted=true;lv.playsInline=true;await lv.play().catch(()=>{});$('localPlaceholder').classList.add('hidden');cameraOn=localStream.getVideoTracks().some(t=>t.enabled);micOn=localStream.getAudioTracks().some(t=>t.enabled);return true}catch(e){console.warn('getUserMedia failed',e);alert('Camera and microphone permission is required. Please allow access and try again.');return false}}
async function send(m){if(!signal)return;try{await api('/api/signal',{method:'POST',body:JSON.stringify(m)})}catch(e){console.warn(e)}}
async function playRemote(){const rv=$('remoteVideo');try{await rv.play()}catch(e){console.warn('Remote autoplay blocked',e);status('Tap the video to play');rv.onclick=()=>rv.play().catch(()=>{})}}
async function flushPendingIce(){if(!pc||!pc.remoteDescription)return;const items=pendingIce.splice(0);for(const c of items){try{await pc.addIceCandidate(c)}catch(e){console.warn('ICE candidate failed',e)}}}
async function createPeer(){if(pc)return;pendingIce=[];remoteStream=new MediaStream();const rv=$('remoteVideo');rv.srcObject=remoteStream;rv.autoplay=true;rv.playsInline=true;rv.muted=false;pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'},{urls:'stun:stun2.l.google.com:19302'}],bundlePolicy:'max-bundle',iceCandidatePoolSize:4});for(const t of localStream.getTracks())pc.addTrack(t,localStream);pc.ontrack=e=>{if(!remoteStream)remoteStream=new MediaStream();if(!remoteStream.getTracks().some(t=>t.id===e.track.id))remoteStream.addTrack(e.track);rv.srcObject=remoteStream;e.track.onunmute=()=>{if(e.track.kind==='video'){$('remotePlaceholder').classList.add('hidden');status('Video connected')}playRemote()};if(e.track.kind==='video')$('remotePlaceholder').classList.add('hidden');playRemote()};pc.onicecandidate=e=>{if(e.candidate)send({type:'ice',candidate:e.candidate.toJSON?e.candidate.toJSON():e.candidate})};pc.onconnectionstatechange=()=>{if(!pc)return;if(pc.connectionState==='connected')status('Connected');if(['failed','disconnected'].includes(pc.connectionState))status('Connection interrupted')};pc.oniceconnectionstatechange=()=>{if(pc&&pc.iceConnectionState==='failed')pc.restartIce?.()}}
async function offer(){const o=await pc.createOffer({offerToReceiveAudio:true,offerToReceiveVideo:true});await pc.setLocalDescription(o);await send({type:'offer',offer:{type:pc.localDescription.type,sdp:pc.localDescription.sdp}})}
function cleanupPeer(){pendingIce=[];if(pc){pc.ontrack=null;pc.onicecandidate=null;pc.close();pc=null}if(remoteStream){remoteStream.getTracks().forEach(t=>t.stop());remoteStream=null}const rv=$('remoteVideo');rv.pause();rv.srcObject=null;rv.onclick=null;$('remotePlaceholder').classList.remove('hidden')}
async function handleSignal(m){if(m.type==='matched'){role=m.role;$('partnerName').textContent=m.partner||'Guest';hide(matching);show(chatScreen);$('messages').innerHTML='';addMessage('You are connected. Be respectful.');await createPeer();if(role==='caller')await offer();return}if(m.type==='offer'){if(!pc)await createPeer();await pc.setRemoteDescription(new RTCSessionDescription(m.offer));await flushPendingIce();const a=await pc.createAnswer();await pc.setLocalDescription(a);await send({type:'answer',answer:{type:pc.localDescription.type,sdp:pc.localDescription.sdp}});return}if(m.type==='answer'){if(pc){await pc.setRemoteDescription(new RTCSessionDescription(m.answer));await flushPendingIce()}return}if(m.type==='ice'&&m.candidate){const c=new RTCIceCandidate(m.candidate);if(pc?.remoteDescription){try{await pc.addIceCandidate(c)}catch(e){console.warn('ICE candidate failed',e)}}else pendingIce.push(c);return}if(m.type==='chat'){addMessage(`${m.username||'Guest'}: ${m.text}`,'them');return}if(m.type==='hangup'){cleanupPeer();addMessage('Guest disconnected.');status('Guest disconnected')}}
async function pollSignal(){if(!signal||pollBusy)return;pollBusy=true;try{const d=await api('/api/signal');for(const m of d.messages||[])await handleSignal(m)}catch(e){console.warn(e)}finally{pollBusy=false}}
async function connectSignal(){signal=true;await send({type:'find'});await pollSignal();clearInterval(pollTimer);pollTimer=setInterval(pollSignal,900)}
$('findBtn').onclick=async()=>{username=user.username;hide(profile);show(matching);const ok=await startCamera();if(!ok){hide(matching);show(profile);return}connectSignal()};$('cancelBtn').onclick=()=>{closeAll();hide(matching);show(profile)};function closeAll(){if(signal)send({type:'hangup'});clearInterval(pollTimer);pollTimer=null;signal=null;cleanupPeer();localStream?.getTracks().forEach(t=>t.stop());localStream=null}
$('sendBtn').onclick=sendMessage;$('messageInput').onkeydown=e=>{if(e.key==='Enter')sendMessage()};function sendMessage(){const text=$('messageInput').value.trim();if(!text)return;addMessage(`You: ${text}`,'me');send({type:'chat',username,text});$('messageInput').value=''}$('nextBtn').onclick=()=>{cleanupPeer();$('messages').innerHTML='';addMessage('Finding another safe match...');send({type:'next'});status('Finding another guest...')};$('endBtn').onclick=()=>{closeAll();hide(chatScreen);show(profile)};$('micBtn').onclick=()=>{if(!localStream)return;micOn=!micOn;localStream.getAudioTracks().forEach(t=>t.enabled=micOn);$('micBtn').textContent=micOn?'🎤':'🔇'};$('cameraBtn').onclick=()=>{if(!localStream)return;cameraOn=!cameraOn;localStream.getVideoTracks().forEach(t=>t.enabled=cameraOn);$('cameraBtn').textContent=cameraOn?'📷':'🚫';$('localPlaceholder').classList.toggle('hidden',cameraOn)};$('blockBtn').onclick=()=>{if(!confirm('Block this guest?'))return;send({type:'block'});cleanupPeer();addMessage('Guest blocked.');status('Guest blocked')};$('reportBtn').onclick=()=>{const reason=prompt('Why are you reporting this guest?','Inappropriate behavior');if(reason===null)return;send({type:'report',reason});cleanupPeer();addMessage('Report submitted. Thank you for helping keep NovaChat safe.');status('Report submitted')};loadMe();
